### ISSUE TITLE
Delayed EQ's (Still in-time for alert.)

### ISSUE THREAD

**Issue by Luarst** [Kxze/PSO2-EQ-API#3]
Racing the Phantom Mother wasn't on the EQ list when I got a Beach Wars alert. (The scheduled one that happened two hours after it.) 

Kinda sad as that made my "Next alert time in # hours." that I've added skip to the EQ after.
![thanks](https://user-images.githubusercontent.com/17341158/29776949-efe584fc-8bcf-11e7-9f04-352f2f59bc86.png)

**Comment by Kxze** [comment]
The API doesn't support future alerts yet, . I'm still trying to figure out how I want to implement that. Maybe serve three objects, one for the EQ that's happening in an hour, one for the past EQs, and one for the scheduled EQs? That also saves some performance for the clients using it, as you can check if there are any EQs happening at the moment before performing any I/O operations. We'll see.

**Comment by Luarst** [comment]
Alright. I had assumed that every notification on the twitter should be inside the data. Thanks for telling me this.
